// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// PlusCal algorithm generator for tlaiser.
//
// PlusCal is an imperative front-end for TLA+ designed by Leslie Lamport.
// It provides a more readable syntax for specifying algorithms while
// compiling down to TLA+ for model checking. This module generates
// PlusCal `algorithm` blocks embedded in `.tla` files.
//
// The generated PlusCal uses the "fair algorithm" form with labeled
// states and `either/or` branches for non-deterministic transitions.

use crate::abi::{Property, StateMachine};

/// Generate a TLA+ file containing a PlusCal algorithm block.
///
/// The output is a valid `.tla` file with:
/// 1. A TLA+ module header
/// 2. A `(* --algorithm ... end algorithm; *)` block
/// 3. A translation placeholder where TLC's PlusCal translator
///    will insert the generated TLA+
/// 4. Property definitions
///
/// The PlusCal algorithm models the state machine as a while loop
/// with an `either/or` dispatch on the current state.
pub fn generate_pluscal(sm: &StateMachine, properties: &[Property]) -> String {
    let mut out = String::new();

    // Module header
    let sep = "-".repeat(4);
    out.push_str(&format!("{} MODULE {}PlusCal {}\n", sep, sm.name, sep));
    if let Some(ref desc) = sm.description {
        out.push_str(&format!("\\* {}\n", desc));
    }
    out.push_str("\\* PlusCal version — generated by tlaiser\n");
    out.push_str("\\* https://github.com/hyperpolymath/tlaiser\n");
    out.push('\n');
    out.push_str("EXTENDS Naturals, Sequences, TLC\n");
    out.push('\n');

    // State constants (same as in the TLA+ spec)
    let state_names: Vec<&str> = sm.states.iter().map(|s| s.name.as_str()).collect();
    out.push_str(&format!("CONSTANTS {}\n", state_names.join(", ")));
    out.push('\n');

    // PlusCal algorithm block
    out.push_str(&generate_algorithm_block(sm));
    out.push('\n');

    // Translation placeholder
    out.push_str("\\* BEGIN TRANSLATION\n");
    out.push_str("\\* (PlusCal translator will insert TLA+ here)\n");
    out.push_str("\\* END TRANSLATION\n");
    out.push('\n');

    // Properties
    if !properties.is_empty() {
        out.push_str(&generate_pluscal_properties(properties));
    }

    out.push_str("====\n");
    out
}

/// Generate the PlusCal algorithm block.
///
/// Structure:
/// ```text
/// (* --fair algorithm MachineName
/// variables
///     state = InitialState;
///     var1 = init1;
///     ...
/// begin
/// MainLoop:
///     while TRUE do
///         either  \* transitions from state A
///             await state = A;
///             ...
///         or      \* transitions from state B
///             ...
///         end either;
///     end while;
/// end algorithm; *)
/// ```
fn generate_algorithm_block(sm: &StateMachine) -> String {
    let mut out = String::new();

    out.push_str(&format!("(* --fair algorithm {}\n", sm.name));

    // Variables section
    out.push_str("variables\n");
    out.push_str(&format!("    state = {};\n", sm.initial_state));
    for var in &sm.variables {
        out.push_str(&format!("    {} = {};\n", var.name, var.init));
    }

    // Begin block
    out.push_str("begin\n");
    out.push_str("MainLoop:\n");
    out.push_str("    while TRUE do\n");

    // Group transitions by source state for the either/or dispatch
    let grouped = group_transitions_by_source(sm);

    if grouped.is_empty() {
        out.push_str("        skip; \\* No transitions defined\n");
    } else {
        let mut first_group = true;
        for (source_state, transitions) in &grouped {
            if first_group {
                out.push_str("        either\n");
                first_group = false;
            } else {
                out.push_str("        or\n");
            }

            // Each group of transitions from the same source state
            if transitions.len() == 1 {
                let t = &transitions[0];
                generate_single_transition(&mut out, source_state, t, sm, "            ");
            } else {
                // Multiple transitions from same state: nested either/or
                out.push_str(&format!("            await state = {};\n", source_state));
                let mut first_inner = true;
                for t in transitions {
                    if first_inner {
                        out.push_str("            either\n");
                        first_inner = false;
                    } else {
                        out.push_str("            or\n");
                    }
                    generate_transition_body(&mut out, t, sm, "                ");
                }
                out.push_str("            end either;\n");
            }
        }
        out.push_str("        end either;\n");
    }

    out.push_str("    end while;\n");
    out.push_str("end algorithm; *)\n");

    out
}

/// Generate a single transition within the PlusCal either/or block.
///
/// Includes the await guard, state update, action, and label comment.
fn generate_single_transition(
    out: &mut String,
    source_state: &str,
    transition: &TransitionInfo,
    sm: &StateMachine,
    indent: &str,
) {
    // Label comment
    if let Some(ref label) = transition.label {
        out.push_str(&format!("{}\\* {}\n", indent, label));
    }

    // Await on current state
    out.push_str(&format!("{}await state = {};\n", indent, source_state));

    generate_transition_body(out, transition, sm, indent);
}

/// Generate the body of a transition (guard check, state update, action).
fn generate_transition_body(
    out: &mut String,
    transition: &TransitionInfo,
    _sm: &StateMachine,
    indent: &str,
) {
    // Guard condition
    if let Some(ref guard) = transition.guard {
        out.push_str(&format!("{}await {};\n", indent, guard));
    }

    // State update
    out.push_str(&format!("{}state := {};\n", indent, transition.to));

    // Action (variable updates)
    if let Some(ref action) = transition.action {
        // Convert TLA+ primed notation to PlusCal assignment
        let pcal_action = tla_action_to_pluscal(action);
        out.push_str(&format!("{}{}\n", indent, pcal_action));
    }
}

/// Information about a transition, extracted from the ABI types.
struct TransitionInfo {
    to: String,
    guard: Option<String>,
    action: Option<String>,
    label: Option<String>,
}

/// Group transitions by their source state.
///
/// Returns a vector of (source_state, transitions) pairs, preserving
/// the order of first appearance.
fn group_transitions_by_source(sm: &StateMachine) -> Vec<(String, Vec<TransitionInfo>)> {
    let mut groups: Vec<(String, Vec<TransitionInfo>)> = Vec::new();

    for t in &sm.transitions {
        let info = TransitionInfo {
            to: t.to.clone(),
            guard: t.guard.clone(),
            action: t.action.clone(),
            label: t.label.clone(),
        };

        if let Some(group) = groups.iter_mut().find(|(src, _)| src == &t.from) {
            group.1.push(info);
        } else {
            groups.push((t.from.clone(), vec![info]));
        }
    }

    groups
}

/// Convert TLA+ action notation to PlusCal assignments.
///
/// TLA+ uses primed variables (`var' = expr`), while PlusCal uses
/// `:=` assignment (`var := expr`). This performs a simple syntactic
/// conversion. For complex actions, users should write PlusCal directly.
fn tla_action_to_pluscal(action: &str) -> String {
    // Replace `var' = expr` patterns with `var := expr`
    // Split on `/\` conjuncts and process each
    let conjuncts: Vec<&str> = action.split("/\\").collect();
    let mut result_parts = Vec::new();

    for conjunct in conjuncts {
        let trimmed = conjunct.trim();
        if trimmed.is_empty() {
            continue;
        }

        // Look for `name' = value` pattern
        if let Some(prime_pos) = trimmed.find('\'') {
            let var_name = trimmed[..prime_pos].trim();
            let rest = trimmed[prime_pos + 1..].trim();
            if let Some(eq_rest) = rest.strip_prefix('=') {
                let value = eq_rest.trim();
                result_parts.push(format!("{} := {};", var_name, value));
                continue;
            }
        }

        // Fallback: include as a comment
        result_parts.push(format!("\\* {}", trimmed));
    }

    result_parts.join("\n")
}

/// Generate property definitions for PlusCal output.
///
/// These are appended after the translation placeholder, same format
/// as the TLA+ spec properties.
fn generate_pluscal_properties(properties: &[Property]) -> String {
    let mut section = String::new();

    section.push_str("\\* ---- Temporal Properties ----\n");

    for prop in properties {
        section.push_str(&format!("\\* Property: {} ({})\n", prop.name, prop.kind));
        let prop_id = sanitize_pcal_identifier(&prop.name);
        match prop.kind.as_str() {
            "safety" => {
                section.push_str(&format!("{} == []({})\n", prop_id, prop.formula));
            }
            "liveness" => {
                section.push_str(&format!("{} == <>({})\n", prop_id, prop.formula));
            }
            "fairness" => {
                section.push_str(&format!("{} == {}\n", prop_id, prop.formula));
            }
            _ => {
                section.push_str(&format!("{} == {}\n", prop_id, prop.formula));
            }
        }
        section.push('\n');
    }

    section
}

/// Sanitize a property name to be a valid TLA+ identifier.
fn sanitize_pcal_identifier(name: &str) -> String {
    let mut result = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            result.push(ch);
        } else {
            result.push('_');
        }
    }
    if result.is_empty() || !result.chars().next().unwrap().is_ascii_alphabetic() {
        result.insert_str(0, "Prop_");
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::abi::{State, StateMachine, Transition, Variable};

    fn test_machine() -> StateMachine {
        StateMachine {
            name: "MutexProtocol".to_string(),
            states: vec![
                State {
                    name: "Idle".into(),
                    description: None,
                },
                State {
                    name: "Waiting".into(),
                    description: None,
                },
                State {
                    name: "Critical".into(),
                    description: None,
                },
            ],
            initial_state: "Idle".into(),
            transitions: vec![
                Transition {
                    from: "Idle".into(),
                    to: "Waiting".into(),
                    guard: None,
                    action: None,
                    label: Some("request".into()),
                },
                Transition {
                    from: "Waiting".into(),
                    to: "Critical".into(),
                    guard: Some("lock = FALSE".into()),
                    action: Some("lock' = TRUE".into()),
                    label: Some("acquire".into()),
                },
                Transition {
                    from: "Critical".into(),
                    to: "Idle".into(),
                    guard: None,
                    action: Some("lock' = FALSE".into()),
                    label: Some("release".into()),
                },
            ],
            variables: vec![Variable {
                name: "lock".into(),
                init: "FALSE".into(),
                type_hint: Some("BOOLEAN".into()),
            }],
            description: Some("Simple mutex protocol".into()),
        }
    }

    #[test]
    fn test_pluscal_contains_algorithm_block() {
        let sm = test_machine();
        let output = generate_pluscal(&sm, &[]);
        assert!(output.contains("--fair algorithm MutexProtocol"));
        assert!(output.contains("end algorithm;"));
    }

    #[test]
    fn test_pluscal_contains_variables() {
        let sm = test_machine();
        let output = generate_pluscal(&sm, &[]);
        assert!(output.contains("state = Idle"));
        assert!(output.contains("lock = FALSE"));
    }

    #[test]
    fn test_pluscal_contains_transitions() {
        let sm = test_machine();
        let output = generate_pluscal(&sm, &[]);
        assert!(output.contains("state := Waiting"));
        assert!(output.contains("state := Critical"));
        assert!(output.contains("state := Idle"));
    }

    #[test]
    fn test_pluscal_has_module_structure() {
        let sm = test_machine();
        let output = generate_pluscal(&sm, &[]);
        assert!(output.contains("MODULE MutexProtocolPlusCal"));
        assert!(output.contains("EXTENDS Naturals"));
        assert!(output.ends_with("====\n"));
    }

    #[test]
    fn test_tla_action_to_pluscal_conversion() {
        let result = tla_action_to_pluscal("count' = count + 1");
        assert!(result.contains("count := count + 1"));
    }

    #[test]
    fn test_pluscal_with_properties() {
        let sm = test_machine();
        let props = vec![Property {
            name: "NoDeadlock".into(),
            kind: "liveness".into(),
            formula: "state = Critical".into(),
        }];
        let output = generate_pluscal(&sm, &props);
        assert!(output.contains("NoDeadlock"));
        assert!(output.contains("<>("));
    }
}
