// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// TLA+ specification generator for tlaiser.
//
// Generates complete `.tla` files from state machine definitions,
// including:
// - Module header with EXTENDS
// - CONSTANTS for state names
// - VARIABLES declaration
// - Init predicate
// - Next-state relation (disjunction of transition actions)
// - Per-transition action operators
// - Temporal properties (safety invariants, liveness, fairness)
// - Specification formula combining Init, Next, and fairness

use crate::abi::{Property, StateMachine};

/// Generate a complete TLA+ specification file for a state machine.
///
/// The generated spec follows Lamport's standard structure:
/// ```text
/// ---- MODULE Name ----
/// EXTENDS Naturals, Sequences, TLC
/// CONSTANTS ...
/// VARIABLES ...
/// Init == ...
/// Next == ...
/// Spec == Init /\ [][Next]_vars /\ Fairness
/// Properties ...
/// ====
/// ```
pub fn generate_tla_spec(sm: &StateMachine, properties: &[Property]) -> String {
    let mut out = String::new();

    // Module header
    out.push_str(&generate_module_header(sm));
    out.push('\n');

    // Constants
    out.push_str(&generate_constants(sm));
    out.push('\n');

    // Variables
    out.push_str(&generate_variables(sm));
    out.push('\n');

    // Type invariant
    out.push_str(&generate_type_invariant(sm));
    out.push('\n');

    // Init predicate
    out.push_str(&generate_init(sm));
    out.push('\n');

    // Transition actions
    out.push_str(&generate_transition_actions(sm));
    out.push('\n');

    // Next-state relation
    out.push_str(&generate_next(sm));
    out.push('\n');

    // Variables tuple (for stuttering)
    out.push_str(&generate_vars_tuple(sm));
    out.push('\n');

    // Specification formula
    out.push_str(&generate_spec(sm));
    out.push('\n');

    // Properties
    if !properties.is_empty() {
        out.push_str(&generate_properties(properties));
        out.push('\n');
    }

    // Module footer
    out.push_str(&generate_module_footer());

    out
}

/// Generate the TLA+ module header line and EXTENDS clause.
fn generate_module_header(sm: &StateMachine) -> String {
    let separator = "-".repeat(4);
    let mut header = String::new();

    // TLA+ module header
    header.push_str(&format!("{} MODULE {} {}\n", separator, sm.name, separator));

    // Description as a comment
    if let Some(ref desc) = sm.description {
        header.push_str(&format!("\\* {}\n", desc));
    }
    header.push_str("\\* Generated by tlaiser — https://github.com/hyperpolymath/tlaiser\n");
    header.push('\n');

    // EXTENDS clause — Naturals for arithmetic, Sequences for traces, TLC for printing
    header.push_str("EXTENDS Naturals, Sequences, TLC\n");

    header
}

/// Generate CONSTANTS declarations for state names.
///
/// Each state becomes a TLA+ CONSTANT, allowing the model checker
/// to treat them as distinct symbolic values.
fn generate_constants(sm: &StateMachine) -> String {
    let mut section = String::new();

    section.push_str("\\* State constants — each represents a distinct state\n");
    let state_names: Vec<&str> = sm.states.iter().map(|s| s.name.as_str()).collect();
    section.push_str(&format!("CONSTANTS {}\n", state_names.join(", ")));

    section
}

/// Generate VARIABLES declarations.
///
/// Always includes the implicit `state` variable. Additional variables
/// from the state machine definition are included as well.
fn generate_variables(sm: &StateMachine) -> String {
    let mut section = String::new();

    section.push_str("\\* Variables tracked by this specification\n");
    let mut var_names: Vec<&str> = vec!["state"];
    for v in &sm.variables {
        var_names.push(v.name.as_str());
    }
    section.push_str(&format!("VARIABLES {}\n", var_names.join(", ")));

    section
}

/// Generate a type invariant that constrains the state variable
/// to the declared set of states.
fn generate_type_invariant(sm: &StateMachine) -> String {
    let mut section = String::new();

    let state_set: Vec<&str> = sm.states.iter().map(|s| s.name.as_str()).collect();
    section.push_str("\\* Type invariant: state is always one of the declared states\n");
    section.push_str(&format!(
        "TypeInvariant == state \\in {{{}}}\n",
        state_set.join(", ")
    ));

    section
}

/// Generate the Init predicate.
///
/// Sets the `state` variable to the initial state and initialises
/// all auxiliary variables to their declared initial values.
fn generate_init(sm: &StateMachine) -> String {
    let mut section = String::new();

    section.push_str("\\* Initial state predicate\n");
    section.push_str("Init ==\n");
    section.push_str(&format!("    /\\ state = {}\n", sm.initial_state));

    for var in &sm.variables {
        section.push_str(&format!("    /\\ {} = {}\n", var.name, var.init));
    }

    section
}

/// Generate individual action operators for each transition.
///
/// Each transition becomes a named TLA+ operator of the form:
/// ```text
/// ActionName ==
///     /\ state = FromState
///     /\ guard_condition    \* if present
///     /\ state' = ToState
///     /\ action_body        \* if present
///     /\ UNCHANGED <<other_vars>>
/// ```
fn generate_transition_actions(sm: &StateMachine) -> String {
    let mut section = String::new();

    section.push_str("\\* Transition actions\n");

    for (i, t) in sm.transitions.iter().enumerate() {
        // Derive action name from label or generate one
        let action_name = match &t.label {
            Some(lbl) => sanitize_identifier(lbl),
            None => format!("Trans_{}_{}", t.from, t.to),
        };

        section.push_str(&format!(
            "\\* Transition: {} -> {}{}\n",
            t.from,
            t.to,
            t.label
                .as_ref()
                .map(|l| format!(" ({})", l))
                .unwrap_or_default()
        ));
        section.push_str(&format!("{} ==\n", action_name));
        section.push_str(&format!("    /\\ state = {}\n", t.from));

        // Guard condition
        if let Some(ref guard) = t.guard {
            section.push_str(&format!("    /\\ {}\n", guard));
        }

        // State update
        section.push_str(&format!("    /\\ state' = {}\n", t.to));

        // Action body (variable updates)
        if let Some(ref action) = t.action {
            section.push_str(&format!("    /\\ {}\n", action));
        }

        // UNCHANGED for variables not modified by this transition
        let changed_vars = extract_primed_vars(t.action.as_deref());
        let unchanged: Vec<&str> = sm
            .variables
            .iter()
            .filter(|v| !changed_vars.contains(&v.name.as_str()))
            .map(|v| v.name.as_str())
            .collect();

        if !unchanged.is_empty() {
            if unchanged.len() == 1 {
                section.push_str(&format!("    /\\ UNCHANGED {}\n", unchanged[0]));
            } else {
                section.push_str(&format!("    /\\ UNCHANGED <<{}>>\n", unchanged.join(", ")));
            }
        }

        if i < sm.transitions.len() - 1 {
            section.push('\n');
        }
    }

    section
}

/// Generate the Next-state relation as a disjunction of all transitions.
fn generate_next(sm: &StateMachine) -> String {
    let mut section = String::new();

    section.push_str("\\* Next-state relation: disjunction of all transitions\n");
    section.push_str("Next ==\n");

    if sm.transitions.is_empty() {
        section.push_str("    FALSE \\* No transitions defined\n");
    } else {
        for (i, t) in sm.transitions.iter().enumerate() {
            let action_name = match &t.label {
                Some(lbl) => sanitize_identifier(lbl),
                None => format!("Trans_{}_{}", t.from, t.to),
            };
            let prefix = if i == 0 { "    " } else { "    \\/ " };
            section.push_str(&format!(
                "{}{}\n",
                prefix,
                if i == 0 {
                    format!("\\/ {}", action_name)
                } else {
                    action_name
                }
            ));
        }
    }

    section
}

/// Generate the vars tuple for stuttering steps.
fn generate_vars_tuple(sm: &StateMachine) -> String {
    let mut section = String::new();

    let mut all_vars: Vec<&str> = vec!["state"];
    for v in &sm.variables {
        all_vars.push(v.name.as_str());
    }

    section.push_str("\\* All variables tuple (for stuttering)\n");
    section.push_str(&format!("vars == <<{}>>\n", all_vars.join(", ")));

    section
}

/// Generate the Spec formula combining Init, Next, and optional fairness.
fn generate_spec(sm: &StateMachine) -> String {
    let mut section = String::new();

    section.push_str("\\* Complete specification\n");
    section.push_str("Spec == Init /\\ [][Next]_vars\n");
    section.push('\n');

    // Fair specification with weak fairness on all transitions
    section.push_str("\\* Fair specification (with weak fairness on Next)\n");
    section.push_str("FairSpec == Spec /\\ WF_vars(Next)\n");

    // If the machine name is useful, note it
    let _ = sm; // suppress unused warning in this branch

    section
}

/// Generate property definitions from the manifest.
///
/// Safety properties become invariant checks (`[]P`).
/// Liveness properties become temporal formulas (`<>P`).
/// Fairness properties are included as-is.
fn generate_properties(properties: &[Property]) -> String {
    let mut section = String::new();

    section.push_str("\\* ---- Temporal Properties ----\n");

    for prop in properties {
        section.push_str(&format!("\\* Property: {} ({})\n", prop.name, prop.kind));
        let prop_id = sanitize_identifier(&prop.name);
        match prop.kind.as_str() {
            "safety" => {
                section.push_str(&format!("{} == []({})\n", prop_id, prop.formula));
            }
            "liveness" => {
                section.push_str(&format!("{} == <>({})\n", prop_id, prop.formula));
            }
            "fairness" => {
                // Fairness formulas are included verbatim
                section.push_str(&format!("{} == {}\n", prop_id, prop.formula));
            }
            _ => {
                section.push_str(&format!(
                    "\\* WARNING: unknown kind '{}', including verbatim\n",
                    prop.kind
                ));
                section.push_str(&format!("{} == {}\n", prop_id, prop.formula));
            }
        }
        section.push('\n');
    }

    section
}

/// Generate the TLA+ module footer.
fn generate_module_footer() -> String {
    "====\n".to_string()
}

/// Sanitize a string to be a valid TLA+ identifier.
///
/// Replaces non-alphanumeric characters with underscores and ensures
/// the result starts with a letter.
fn sanitize_identifier(name: &str) -> String {
    let mut result = String::with_capacity(name.len());
    for (i, ch) in name.chars().enumerate() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            result.push(ch);
        } else {
            result.push('_');
        }
        // Ensure first character is a letter
        if i == 0 && !ch.is_ascii_alphabetic() {
            result.clear();
            result.push_str("Action_");
            if ch.is_ascii_alphanumeric() {
                result.push(ch);
            }
        }
    }
    if result.is_empty() {
        result.push_str("UnnamedAction");
    }
    result
}

/// Extract variable names that appear as primed (`var'`) in an action string.
///
/// This is a simple heuristic: look for `identifier'` patterns. It is not
/// a full TLA+ parser but sufficient for UNCHANGED clause generation.
fn extract_primed_vars(action: Option<&str>) -> Vec<&str> {
    let Some(action) = action else {
        return Vec::new();
    };

    let mut vars = Vec::new();
    let bytes = action.as_bytes();
    let len = bytes.len();
    let mut i = 0;

    while i < len {
        // Look for an identifier followed by a prime (')
        if bytes[i].is_ascii_alphabetic() || bytes[i] == b'_' {
            let start = i;
            while i < len && (bytes[i].is_ascii_alphanumeric() || bytes[i] == b'_') {
                i += 1;
            }
            if i < len && bytes[i] == b'\'' {
                let var_name = &action[start..i];
                if !vars.contains(&var_name) {
                    vars.push(var_name);
                }
                i += 1;
            }
        } else {
            i += 1;
        }
    }

    vars
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::abi::{State, StateMachine, Transition, Variable};

    /// Build a test state machine with two states and one transition.
    fn test_machine() -> StateMachine {
        StateMachine {
            name: "TestSpec".to_string(),
            states: vec![
                State {
                    name: "Idle".into(),
                    description: None,
                },
                State {
                    name: "Running".into(),
                    description: None,
                },
            ],
            initial_state: "Idle".into(),
            transitions: vec![Transition {
                from: "Idle".into(),
                to: "Running".into(),
                guard: None,
                action: None,
                label: Some("start".into()),
            }],
            variables: vec![],
            description: Some("Test specification".into()),
        }
    }

    #[test]
    fn test_module_header_contains_name() {
        let sm = test_machine();
        let header = generate_module_header(&sm);
        assert!(header.contains("MODULE TestSpec"));
        assert!(header.contains("EXTENDS Naturals"));
    }

    #[test]
    fn test_init_references_initial_state() {
        let sm = test_machine();
        let init = generate_init(&sm);
        assert!(init.contains("state = Idle"));
    }

    #[test]
    fn test_next_includes_all_transitions() {
        let sm = test_machine();
        let next = generate_next(&sm);
        assert!(next.contains("start"));
    }

    #[test]
    fn test_full_spec_is_valid_structure() {
        let sm = test_machine();
        let props = vec![Property {
            name: "Safe".into(),
            kind: "safety".into(),
            formula: "state \\in {Idle, Running}".into(),
        }];
        let spec = generate_tla_spec(&sm, &props);

        // Must start with module header and end with footer
        assert!(spec.contains("---- MODULE TestSpec ----"));
        assert!(spec.ends_with("====\n"));

        // Must contain key sections
        assert!(spec.contains("VARIABLES state"));
        assert!(spec.contains("Init =="));
        assert!(spec.contains("Next =="));
        assert!(spec.contains("Spec =="));
        assert!(spec.contains("[]("));
    }

    #[test]
    fn test_variables_in_spec() {
        let mut sm = test_machine();
        sm.variables.push(Variable {
            name: "count".into(),
            init: "0".into(),
            type_hint: Some("0..10".into()),
        });
        let spec = generate_tla_spec(&sm, &[]);
        assert!(spec.contains("VARIABLES state, count"));
        assert!(spec.contains("count = 0"));
    }

    #[test]
    fn test_sanitize_identifier() {
        assert_eq!(sanitize_identifier("hello"), "hello");
        assert_eq!(sanitize_identifier("has space"), "has_space");
        assert_eq!(sanitize_identifier("CamelCase"), "CamelCase");
    }

    #[test]
    fn test_extract_primed_vars() {
        let vars = extract_primed_vars(Some("count' = count + 1 /\\ flag' = TRUE"));
        assert!(vars.contains(&"count"));
        assert!(vars.contains(&"flag"));
        assert_eq!(vars.len(), 2);

        let empty = extract_primed_vars(None);
        assert!(empty.is_empty());
    }

    #[test]
    fn test_properties_generation() {
        let props = vec![
            Property {
                name: "MutualExclusion".into(),
                kind: "safety".into(),
                formula: "~(pc[1] = \"cs\" /\\ pc[2] = \"cs\")".into(),
            },
            Property {
                name: "EventualEntry".into(),
                kind: "liveness".into(),
                formula: "pc[1] = \"cs\"".into(),
            },
        ];
        let output = generate_properties(&props);
        assert!(output.contains("[]("));
        assert!(output.contains("<>("));
        assert!(output.contains("MutualExclusion"));
        assert!(output.contains("EventualEntry"));
    }
}
