// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// TLC model checker configuration generator for tlaiser.
//
// Generates `.cfg` configuration files and shell commands for running
// the TLC model checker against generated TLA+ specifications. TLC is
// the exhaustive state-space explorer for TLA+ created by Yuan Yu.
//
// The `.cfg` file tells TLC:
// - Which specification to check (SPECIFICATION)
// - Constant assignments (CONSTANT)
// - Invariants to verify (INVARIANT)
// - Temporal properties to check (PROPERTY)
// - Symmetry sets for state reduction (SYMMETRY)

use crate::abi::{Property, StateMachine, TlcConfig};

/// Generate a TLC `.cfg` configuration file.
///
/// Maps the state machine definition and properties to TLC directives:
/// - SPECIFICATION: the Spec or FairSpec formula
/// - CONSTANT: state name assignments (each state constant = a model value)
/// - INVARIANT: safety properties (checked as state invariants)
/// - PROPERTY: liveness/fairness properties (checked as temporal formulas)
/// - SYMMETRY: optional symmetry set for state reduction
pub fn generate_tlc_cfg(
    sm: &StateMachine,
    properties: &[Property],
    tlc_config: &TlcConfig,
) -> String {
    let mut out = String::new();

    out.push_str("\\* TLC Configuration for ");
    out.push_str(&sm.name);
    out.push_str("\n\\* Generated by tlaiser\n\n");

    // Specification formula — use FairSpec if liveness properties exist
    let has_liveness = properties.iter().any(|p| p.kind == "liveness" || p.kind == "fairness");
    if has_liveness {
        out.push_str("SPECIFICATION FairSpec\n");
    } else {
        out.push_str("SPECIFICATION Spec\n");
    }
    out.push('\n');

    // Constants — each state name maps to a model value
    out.push_str("\\* State constants as model values\n");
    for state in &sm.states {
        out.push_str(&format!("CONSTANT {} = {}\n", state.name, state.name));
    }
    out.push('\n');

    // Type invariant is always checked
    out.push_str("\\* Type invariant\n");
    out.push_str("INVARIANT TypeInvariant\n");
    out.push('\n');

    // Safety properties as INVARIANTs
    let safety_props: Vec<&Property> = properties.iter().filter(|p| p.kind == "safety").collect();
    if !safety_props.is_empty() {
        out.push_str("\\* Safety properties (invariants)\n");
        for prop in &safety_props {
            out.push_str(&format!("INVARIANT {}\n", sanitize_cfg_name(&prop.name)));
        }
        out.push('\n');
    }

    // Liveness/fairness properties as PROPERTYs
    let temporal_props: Vec<&Property> = properties
        .iter()
        .filter(|p| p.kind == "liveness" || p.kind == "fairness")
        .collect();
    if !temporal_props.is_empty() {
        out.push_str("\\* Liveness and fairness properties\n");
        for prop in &temporal_props {
            out.push_str(&format!("PROPERTY {}\n", sanitize_cfg_name(&prop.name)));
        }
        out.push('\n');
    }

    // Symmetry set (optional)
    if tlc_config.symmetry && sm.states.len() > 1 {
        out.push_str("\\* Symmetry reduction\n");
        let state_names: Vec<&str> = sm.states.iter().map(|s| s.name.as_str()).collect();
        out.push_str(&format!(
            "SYMMETRY Permutations({{{}}})\n",
            state_names.join(", ")
        ));
        out.push('\n');
    }

    out
}

/// Generate a shell script to run TLC on a generated spec.
///
/// The script includes:
/// - The `java -jar tla2tools.jar` command with appropriate flags
/// - Worker count configuration
/// - Max states limit (if set)
/// - Useful environment variable overrides
pub fn generate_run_script(sm: &StateMachine, tlc_config: &TlcConfig) -> String {
    let mut out = String::new();

    out.push_str("#!/usr/bin/env bash\n");
    out.push_str("# SPDX-License-Identifier: PMPL-1.0-or-later\n");
    out.push_str(&format!(
        "# TLC run script for {} — generated by tlaiser\n",
        sm.name
    ));
    out.push_str("# https://github.com/hyperpolymath/tlaiser\n");
    out.push_str("#\n");
    out.push_str("# Prerequisites:\n");
    out.push_str("#   - Java runtime (>= 11)\n");
    out.push_str("#   - tla2tools.jar on CLASSPATH or in current directory\n");
    out.push_str("#   - Or: install Community TLA+ Toolbox\n");
    out.push_str("\n");
    out.push_str("set -euo pipefail\n");
    out.push_str("\n");

    // Locate tla2tools.jar
    out.push_str("# Locate TLA+ tools\n");
    out.push_str("TLA2TOOLS=\"${TLA2TOOLS:-tla2tools.jar}\"\n");
    out.push_str("if [[ ! -f \"$TLA2TOOLS\" ]]; then\n");
    out.push_str("    echo \"Error: tla2tools.jar not found. Set TLA2TOOLS env var or download from:\"\n");
    out.push_str("    echo \"  https://github.com/tlaplus/tlaplus/releases\"\n");
    out.push_str("    exit 1\n");
    out.push_str("fi\n");
    out.push_str("\n");

    // Build the TLC command
    out.push_str(&format!("echo \"Running TLC on {}.tla ...\"\n", sm.name));
    out.push_str(&format!("{}\n", tlc_command(&sm.name, tlc_config)));
    out.push_str("\n");
    out.push_str("echo \"TLC completed.\"\n");

    out
}

/// Build the TLC invocation command string.
///
/// Returns a command like:
/// ```text
/// java -XX:+UseParallelGC -jar "$TLA2TOOLS" -workers 4 -config Spec.cfg Spec.tla
/// ```
pub fn tlc_command(machine_name: &str, tlc_config: &TlcConfig) -> String {
    let mut cmd = String::new();

    cmd.push_str("java -XX:+UseParallelGC");

    // Memory settings for large state spaces
    cmd.push_str(" -Xmx4g");

    cmd.push_str(" -jar \"$TLA2TOOLS\"");

    // TLC-specific flags
    cmd.push_str(&format!(" -workers {}", tlc_config.workers));

    if tlc_config.max_states > 0 {
        cmd.push_str(&format!(" -maxSetSize {}", tlc_config.max_states));
    }

    // Additional flags from config
    for flag in &tlc_config.extra_flags {
        cmd.push_str(&format!(" {}", flag));
    }

    // Config file and spec file
    cmd.push_str(&format!(
        " -config {}.cfg {}.tla",
        machine_name, machine_name
    ));

    cmd
}

/// Generate a summary of TLC analysis commands for display.
///
/// This provides human-readable output showing what TLC will check
/// and how the model is configured.
pub fn generate_analysis_summary(
    sm: &StateMachine,
    properties: &[Property],
    tlc_config: &TlcConfig,
) -> String {
    let mut out = String::new();

    out.push_str(&format!("=== TLC Analysis: {} ===\n", sm.name));
    out.push('\n');

    out.push_str(&format!("States: {}\n", sm.states.len()));
    out.push_str(&format!("Transitions: {}\n", sm.transitions.len()));
    out.push_str(&format!(
        "Variables: {} (+ implicit state)\n",
        sm.variables.len()
    ));
    out.push('\n');

    out.push_str("Properties to check:\n");
    let safety_count = properties.iter().filter(|p| p.kind == "safety").count();
    let liveness_count = properties.iter().filter(|p| p.kind == "liveness").count();
    let fairness_count = properties.iter().filter(|p| p.kind == "fairness").count();
    out.push_str(&format!("  Safety:   {}\n", safety_count));
    out.push_str(&format!("  Liveness: {}\n", liveness_count));
    out.push_str(&format!("  Fairness: {}\n", fairness_count));
    out.push('\n');

    out.push_str(&format!("TLC workers: {}\n", tlc_config.workers));
    out.push_str(&format!(
        "Max states: {}\n",
        if tlc_config.max_states == 0 {
            "unlimited".to_string()
        } else {
            tlc_config.max_states.to_string()
        }
    ));
    out.push_str(&format!("Symmetry: {}\n", tlc_config.symmetry));

    out
}

/// Sanitize a property name for use in a TLC `.cfg` file.
///
/// CFG files reference TLA+ operator names, which must be valid identifiers.
fn sanitize_cfg_name(name: &str) -> String {
    let mut result = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            result.push(ch);
        } else {
            result.push('_');
        }
    }
    if result.is_empty() || !result.chars().next().unwrap().is_ascii_alphabetic() {
        result.insert_str(0, "Prop_");
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::abi::{State, StateMachine, Transition, Variable};

    fn test_machine() -> StateMachine {
        StateMachine {
            name: "MutexSpec".to_string(),
            states: vec![
                State { name: "Idle".into(), description: None },
                State { name: "Waiting".into(), description: None },
                State { name: "Critical".into(), description: None },
            ],
            initial_state: "Idle".into(),
            transitions: vec![
                Transition { from: "Idle".into(), to: "Waiting".into(), guard: None, action: None, label: Some("request".into()) },
                Transition { from: "Waiting".into(), to: "Critical".into(), guard: Some("lock = FALSE".into()), action: Some("lock' = TRUE".into()), label: Some("acquire".into()) },
                Transition { from: "Critical".into(), to: "Idle".into(), guard: None, action: Some("lock' = FALSE".into()), label: Some("release".into()) },
            ],
            variables: vec![Variable {
                name: "lock".into(),
                init: "FALSE".into(),
                type_hint: Some("BOOLEAN".into()),
            }],
            description: None,
        }
    }

    #[test]
    fn test_cfg_contains_specification() {
        let sm = test_machine();
        let props = vec![Property {
            name: "Safe".into(),
            kind: "safety".into(),
            formula: "TRUE".into(),
        }];
        let cfg = generate_tlc_cfg(&sm, &props, &TlcConfig::default());
        assert!(cfg.contains("SPECIFICATION Spec"));
    }

    #[test]
    fn test_cfg_uses_fairspec_for_liveness() {
        let sm = test_machine();
        let props = vec![Property {
            name: "EventualEntry".into(),
            kind: "liveness".into(),
            formula: "state = Critical".into(),
        }];
        let cfg = generate_tlc_cfg(&sm, &props, &TlcConfig::default());
        assert!(cfg.contains("SPECIFICATION FairSpec"));
        assert!(cfg.contains("PROPERTY EventualEntry"));
    }

    #[test]
    fn test_cfg_contains_constants() {
        let sm = test_machine();
        let cfg = generate_tlc_cfg(&sm, &[], &TlcConfig::default());
        assert!(cfg.contains("CONSTANT Idle = Idle"));
        assert!(cfg.contains("CONSTANT Waiting = Waiting"));
        assert!(cfg.contains("CONSTANT Critical = Critical"));
    }

    #[test]
    fn test_cfg_contains_type_invariant() {
        let sm = test_machine();
        let cfg = generate_tlc_cfg(&sm, &[], &TlcConfig::default());
        assert!(cfg.contains("INVARIANT TypeInvariant"));
    }

    #[test]
    fn test_tlc_command_includes_workers() {
        let config = TlcConfig {
            workers: 8,
            max_states: 50000,
            symmetry: false,
            extra_flags: vec![],
        };
        let cmd = tlc_command("TestSpec", &config);
        assert!(cmd.contains("-workers 8"));
        assert!(cmd.contains("-maxSetSize 50000"));
        assert!(cmd.contains("TestSpec.tla"));
        assert!(cmd.contains("TestSpec.cfg"));
    }

    #[test]
    fn test_run_script_is_valid_bash() {
        let sm = test_machine();
        let script = generate_run_script(&sm, &TlcConfig::default());
        assert!(script.starts_with("#!/usr/bin/env bash"));
        assert!(script.contains("set -euo pipefail"));
        assert!(script.contains("TLA2TOOLS"));
    }

    #[test]
    fn test_analysis_summary() {
        let sm = test_machine();
        let props = vec![
            Property { name: "P1".into(), kind: "safety".into(), formula: "TRUE".into() },
            Property { name: "P2".into(), kind: "liveness".into(), formula: "TRUE".into() },
        ];
        let summary = generate_analysis_summary(&sm, &props, &TlcConfig::default());
        assert!(summary.contains("States: 3"));
        assert!(summary.contains("Transitions: 3"));
        assert!(summary.contains("Safety:   1"));
        assert!(summary.contains("Liveness: 1"));
    }

    #[test]
    fn test_symmetry_in_cfg() {
        let sm = test_machine();
        let config = TlcConfig {
            workers: 4,
            max_states: 0,
            symmetry: true,
            extra_flags: vec![],
        };
        let cfg = generate_tlc_cfg(&sm, &[], &config);
        assert!(cfg.contains("SYMMETRY"));
        assert!(cfg.contains("Permutations"));
    }
}
